spring:
  application:
    name: zipkin

server:
  port: 9411

eureka:
  client:
    region: default
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://discovery:8010/eureka

logging:
  level: debug
