version: "3.8"

networks:
  backend:

services:
  discovery:
    container_name: discovery
    image: gza73/agh-praca-inzynierska-discovery:latest
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    ports:
      - 8010:8010
    networks:
      - backend

  gateway:
    container_name: gateway
    image: gza73/agh-praca-inzynierska-gateway:latest
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    ports:
      - 8020:8020
    networks:
      - backend
    depends_on:
      - discovery

  mongodb:
    container_name: mongodb
    image: gza73/agh-praca-inzynierska-mongodb:latest
    ports:
      - 27017:27017
    networks:
      - backend

  auth:
    container_name: auth
    image: gza73/agh-praca-inzynierska-auth:latest
    environment:
      - "SPRING_PROFILES_ACTIVE=docker,production"
    networks:
      - backend
    depends_on:
      - mongodb
      - gateway

  account:
    container_name: account
    image: gza73/agh-praca-inzynierska-account:latest
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    networks:
      - backend
    depends_on:
      - mongodb
      - gateway
      
  gympass:
    container_name: gympass
    image: gza73/agh-praca-inzynierska-gympass:latest
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    networks:
      - backend
    depends_on:
      - mongodb
      - gateway

  redis:
    container_name: redis
    image: gza73/agh-praca-inzynierska-redis:latest
    ports:
      - 6379:6379
    networks:
      - backend
