version: "3.8"

networks:
  backend:

services:
  config-server:
    image: gza73/agh-praca-inzynierska-config-server:latest
    environment:
      - "SPRING_PROFILES_ACTIVE=docker,native"
    volumes:
      - ./properties:/home/healthy-gym-config
    ports:
      - "8030:8030"
    networks:
      - backend
    deploy:
      replicas: 1

  discovery:
    image: gza73/agh-praca-inzynierska-discovery:latest
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    ports:
      - "8010:8010"
    networks:
      - backend
    depends_on:
      - config-server
    deploy:
      replicas: 1

  gateway:
    image: gza73/agh-praca-inzynierska-gateway:latest
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    ports:
      - "8020:8020"
    networks:
      - backend
    depends_on:
      - discovery
    deploy:
      replicas: 1

  mongodb:
    image: gza73/agh-praca-inzynierska-mongodb:latest
    ports:
      - "27017:27017"
    networks:
      - backend
    volumes:
      - ./mongodb/dump:/home/dump
    deploy:
      replicas: 1

  auth:
    image: gza73/agh-praca-inzynierska-auth:latest
    environment:
      - "SPRING_PROFILES_ACTIVE=docker,production"
    networks:
      - backend
    depends_on:
      - mongodb
      - gateway
    deploy:
      replicas: 1

  account:
    image: gza73/agh-praca-inzynierska-account:latest
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    networks:
      - backend
    depends_on:
      - mongodb
      - gateway
    deploy:
      replicas: 1

  trainings:
    image: gza73/agh-praca-inzynierska-trainings:latest
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    networks:
      - backend
    depends_on:
      - mongodb
      - gateway
    deploy:
      replicas: 1

  gympass:
    image: gza73/agh-praca-inzynierska-gympass:latest
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    networks:
      - backend
    depends_on:
      - mongodb
      - gateway
    deploy:
      replicas: 1

  task:
    image: gza73/agh-praca-inzynierska-task:latest
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    networks:
      - backend
    depends_on:
      - mongodb
      - gateway
    deploy:
      replicas: 1

  redis:
    image: gza73/agh-praca-inzynierska-redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend
    deploy:
      replicas: 1

  rabbitmq:
    image: gza73/agh-praca-inzynierska-rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    deploy:
      replicas: 1
    networks:
      - backend

  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - target: 9411
        published: 9411
        mode: host
    deploy:
      replicas: 1
    networks:
      - backend

#  elasticsearch:
#    image: elasticsearch:7.14.0
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    deploy:
#      replicas: 1
#    volumes:
#      - ./logs/:/usr/share/elasticsearch/data
#    environment:
#      - discovery.type=single-node
#    networks:
#      - backend
#
#  logstash:
#    image: logstash:7.14.0
#    ports:
#      - "9600:9600"
#    deploy:
#      replicas: 1
#    volumes:
#      - ./elk/logstash/config/:/usr/share/logstash/pipeline/
#      - ./logs/:/logs/
#    depends_on:
#      - elasticsearch
#    networks:
#      - backend
#
#  kibana:
#    image: kibana:7.14.0
#    ports:
#      - "5601:5601"
#    deploy:
#      replicas: 1
#    depends_on:
#      - elasticsearch
#    networks:
#      - backend