server:
  port: 8080

spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka

ribbon:
  eureka:
    enabled: true
#    isSecure: false
#    ReadTimeout: 60000
#    ConnectTimeout: 60000

zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000