spring:
  application:
    name: trainings
  devtools:
    restart:
      enabled: true
  data:
    mongodb:
      uri: mongodb://adminPracaInz:thisPAsswordNeed2BeChange@localhost:27017/databasePracaInz
      database: databasePracaInz

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

microservice:
  email:
    name: silownia_herkules@vp.pl
    password: sample_password1234
    personal: Siłownia Herkules
  smtp:
    host: smtp.poczta.onet.pl
    port: 587