spring:
  application:
    name: trainings
  devtools:
    restart:
      enabled: true
  data:
    mongodb:
      uri: mongodb://adminPracaInz:thisPAsswordNeed2BeChange@mongodb:27017/databasePracaInz
      database: databasePracaInz
  servlet:
    multipart:
      max-file-size: 5MB
      enabled: true
      max-request-size: 5MB
  rabbitmq:
    host: rabbitmq
    port: 5672
    password: th1sPAsswordNeed2BeChAnged
    username: healthy_gym
  mail:
    host: smtp.gmail.com
    port: 587

server:
  port: 0
  error:
    include-message: always
    include-stacktrace: never
    include-exception: false

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8010/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

#custom settings
token:
  secret: r@ndomlyGener@ted2ecretKey22ecureApplic@tionAndNeed2BeCh@nge1nTheFuture
  expiration-time: 3600000

authorization:
  token:
    header:
      name: Authorization
      prefix: Bearer

front-end:
  protocol: http
  host: localhost
  port: 5000