server:
  port: 8020

spring:
  devtools:
    restart:
      enabled: true
  application:
    name: gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  eureka:
    enabled: true

zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  sensitive-headers:

#custom settings
token:
  secret: r@ndomlyGener@ted2ecretKey22ecureApplic@tionAndNeed2BeCh@nge1nTheFuture

authorization:
  token:
    header:
      name: Authorization
      prefix: Bearer

front-end:
  url: http://localhost:3000