spring:
  application:
    name: auth
  devtools:
    restart:
      enabled: true
  profiles:
    active: production
  redis:
    database: 0
    host: redis
    port: 6379
    test:
      port: 6380
    password: thisP@sswordNeed2BeChange
    timeout: 60000
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb://adminPracaInz:thisPAsswordNeed2BeChange@mongodb:27017/databasePracaInz
      database: databasePracaInz
  rabbitmq:
    host: rabbitmq
    port: 5672
    password: th1sPAsswordNeed2BeChAnged
    username: healthy_gym

server:
  port: 0
  error:
    include-message: always
    include-stacktrace: never
    include-exception: false

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8010/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

#custom settings
token:
  secret: r@ndomlyGener@ted2ecretKey22ecureApplic@tionAndNeed2BeCh@nge1nTheFuture
  expiration-time: 3600000

authorization:
  token:
    header:
      name: Authorization
      prefix: Bearer

front-end:
  protocol: http
  host: localhost
  port: 3000
  homepage: AGH-Praca-inzynierska-front-end