spring:
  data:
    mongodb:
      uri: mongodb://adminPracaInz:thisPAsswordNeed2BeChange@mongodb:27017/databasePracaInz
  rabbitmq:
    host: rabbitmq
  zipkin:
    base-url: http://zipkin:9411

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8010/eureka

logging:
  file:
    path: /logs

#custom settings
front-end:
  port: 5000