version: '3.6'

networks:
  crs:

services:
  mysql-db:
    container_name: mongo-db
    image: mongo:4.4.4-bionic
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      # creating database and adding test data
      - ./DB/init:/docker-entrypoint-initdb.d
    networks:
      - crs