server:
  port: 8030

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/healthy-gym-config
          default-label: main
          clone-on-start: true
    bus:
      enabled: true
      refresh:
        enabled: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    password: th1sPAsswordNeed2BeChAnged
    username: healthy_gym

eureka:
  client:
    region: default
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://discovery:8010/eureka

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh