server:
  port: 8030

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: file:///home/healthy-gym-config
    bus:
      enabled: true
      refresh:
        enabled: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    password: th1sPAsswordNeed2BeChAnged
    username: healthy_gym
  profiles:
    active: native
  zipkin:
    base-url: http://zipkin:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1

eureka:
  client:
    region: default
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://discovery:8010/eureka

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh