name: Back-end CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  discovery:
    name: Discovery service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: Validate
        run: mvn validate --file ./discovery/pom.xml
        
      - name: Compile
        run: mvn compile --file ./discovery/pom.xml
          
      - name: Build
        run: mvn spring-boot:build-info --file ./discovery/pom.xml
        
      - name: Test
        run: mvn test --file ./discovery/pom.xml

  gateway:
    name: Gateway service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: Validate
        run: mvn validate --file ./gateway/pom.xml
        
      - name: Compile
        run: mvn compile --file ./gateway/pom.xml
          
      - name: Build
        run: mvn spring-boot:build-info --file ./gateway/pom.xml
      
      - name: Test
        run: mvn test --file ./gateway/pom.xml

  user:
    name: User service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: Validate
        run: mvn validate --file ./user/pom.xml
        
      - name: Compile
        run: mvn compile --file ./user/pom.xml
          
      - name: Build
        run: mvn spring-boot:build-info --file ./user/pom.xml
      
      - name: Test
        run: mvn test --file ./user/pom.xml

  trainings:
    name: Trainings service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Validate
        run: mvn validate --file ./trainings/pom.xml

      - name: Compile
        run: mvn compile --file ./trainings/pom.xml

      - name: Build
        run: mvn spring-boot:build-info --file ./trainings/pom.xml

      - name: Test
        run: mvn test --file ./trainings/pom.xml
