name: Continuous delivery

on:
  push:
    branches: [ main ]

jobs:
  discovery:
    name: discovery
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Validate
        run: mvn validate --file ./discovery/pom.xml
      - name: Compile
        run: mvn compile --file ./discovery/pom.xml
      - name: Test
        run: mvn test --file ./discovery/pom.xml
      - name: Build app
        run: mvn spring-boot:build-info --file ./discovery/pom.xml
      - name: Build image
        run: mvn spring-boot:build-image --file ./discovery/pom.xml
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to DockerHub
        run: docker push gza73/agh-praca-inzynierska-discovery:latest



  gateway:
    name: gateway
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Validate
        run: mvn validate --file ./gateway/pom.xml
      - name: Compile
        run: mvn compile --file ./gateway/pom.xml
      - name: Test
        run: mvn test --file ./gateway/pom.xml
      - name: Build
        run: mvn spring-boot:build-info --file ./gateway/pom.xml
      - name: Build image
        run: mvn spring-boot:build-image --file ./gateway/pom.xml
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to DockerHub
        run: docker push gza73/agh-praca-inzynierska-gateway:latest
      


  auth:
    name: auth
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Validate
        run: mvn validate --file ./auth/pom.xml
      - name: Compile
        run: mvn compile --file ./auth/pom.xml
      - name: Test
        run: mvn test --file ./auth/pom.xml
      - name: Build
        run: mvn spring-boot:build-info --file ./auth/pom.xml
      - name: Build image
        run: mvn spring-boot:build-image --file ./auth/pom.xml
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to DockerHub
        run: docker push gza73/agh-praca-inzynierska-auth:latest



  trainings:
    name: trainings
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Validate
        run: mvn validate --file ./trainings/pom.xml
      - name: Compile
        run: mvn compile --file ./trainings/pom.xml
      - name: Test
        run: mvn test --file ./trainings/pom.xml
      - name: Build
        run: mvn spring-boot:build-info --file ./trainings/pom.xml
      - name: Build image
        run: mvn spring-boot:build-image --file ./trainings/pom.xml
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to DockerHub
        run: docker push gza73/agh-praca-inzynierska-trainings:latest



  account:
      name: account
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v2
        - name: Set up JDK 11
          uses: actions/setup-java@v1
          with:
            java-version: 11
        - name: Validate
          run: mvn validate --file ./account/pom.xml
        - name: Compile
          run: mvn compile --file ./account/pom.xml
        - name: Test
          run: mvn test --file ./account/pom.xml
        - name: Build
          run: mvn spring-boot:build-info --file ./account/pom.xml
        - name: Build image
          run: mvn spring-boot:build-image --file ./account/pom.xml
        - name: Login to DockerHub
          uses: docker/login-action@v1
          with: 
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Push to DockerHub
          run: docker push gza73/agh-praca-inzynierska-account:latest
  
  
  
  mongodb:
    name: mongodb
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build image
        run: docker build -t gza73/agh-praca-inzynierska-mongodb ./mongodb
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to DockerHub
        run: docker push gza73/agh-praca-inzynierska-mongodb:latest
  
  
  
  redis:
    name: redis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build image
        run: docker build -t gza73/agh-praca-inzynierska-redis ./redis
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to DockerHub
        run: docker push gza73/agh-praca-inzynierska-redis:latest
