name: Continuous integration

on:
  pull_request:
    branches: [ main ]

jobs:
  config-server:
    name: config-server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Validate
        run: mvn validate --file ./config-server/pom.xml
      - name: Compile
        run: mvn compile --file ./config-server/pom.xml
      - name: Test
        run: mvn test --file ./config-server/pom.xml
      - name: Build
        run: mvn spring-boot:build-info --file ./config-server/pom.xml

  discovery:
    name: discovery
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Validate
        run: mvn validate --file ./discovery/pom.xml
      - name: Compile
        run: mvn compile --file ./discovery/pom.xml
      - name: Test
        run: mvn test --file ./discovery/pom.xml
      - name: Build
        run: mvn spring-boot:build-info --file ./discovery/pom.xml
     

  gateway:
    name: gateway
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Validate
        run: mvn validate --file ./gateway/pom.xml
      - name: Compile
        run: mvn compile --file ./gateway/pom.xml
      - name: Test
        run: mvn test --file ./gateway/pom.xml
      - name: Build
        run: mvn spring-boot:build-info --file ./gateway/pom.xml
      


  auth:
    name: auth
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Validate
        run: mvn validate --file ./auth/pom.xml
      - name: Compile
        run: mvn compile --file ./auth/pom.xml
      - name: Test
        run: mvn test --file ./auth/pom.xml
      - name: Build
        run: mvn spring-boot:build-info --file ./auth/pom.xml



  trainings:
    name: trainings
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Validate
        run: mvn validate --file ./trainings/pom.xml
      - name: Compile
        run: mvn compile --file ./trainings/pom.xml
      - name: Test
        run: mvn test --file ./trainings/pom.xml
      - name: Build
        run: mvn spring-boot:build-info --file ./trainings/pom.xml



  account:
      name: account
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v2
        - name: Set up JDK 11
          uses: actions/setup-java@v1
          with:
            java-version: 11
        - name: Validate
          run: mvn validate --file ./account/pom.xml
        - name: Compile
          run: mvn compile --file ./account/pom.xml
        - name: Test
          run: mvn test --file ./account/pom.xml
        - name: Build
          run: mvn spring-boot:build-info --file ./account/pom.xml
          

  gympass:
      name: gympass
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v2
        - name: Set up JDK 11
          uses: actions/setup-java@v1
          with:
            java-version: 11
        - name: Validate
          run: mvn validate --file ./gympass/pom.xml
        - name: Compile
          run: mvn compile --file ./gympass/pom.xml
        - name: Test
          run: mvn test --file ./gympass/pom.xml
        - name: Build
          run: mvn spring-boot:build-info --file ./gympass/pom.xml


  task:
    name: task
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Validate
        run: mvn validate --file ./task/pom.xml
      - name: Compile
        run: mvn compile --file ./task/pom.xml
      - name: Test
        run: mvn test --file ./task/pom.xml
      - name: Build
        run: mvn spring-boot:build-info --file ./task/pom.xml

  equipment:
    name: equipment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Validate
        run: mvn validate --file ./equipment/pom.xml
      - name: Compile
        run: mvn compile --file ./equipment/pom.xml
      - name: Test
        run: mvn test --file ./equipment/pom.xml
      - name: Build
        run: mvn spring-boot:build-info --file ./equipment/pom.xml
